const mongoose = require('../../database'); 

const userSchema = new mongoose.Schema({
  username: { type: String, required: true },
  password: { type: String, required: true },
  profile_image: { type: String }, 
  role: { type: String, required: true },
  token: { type: String },
  displayname: { type: String },
  email: { type: String },
  phone_No: { type: String },
  department: { type: String },
  refreshToken: { type: String },
  status: { type: String, enum: ['active', 'inactive'], default: 'active' },
  permissions: {
    
    company: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
      company_profile: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
        },
      bank: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
        },

    },
    userandpermission: { 
      view: { type: Boolean, default: false }, 
      add: { type: Boolean, default: false }, 
      edit: { type: Boolean, default: false }, 
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false }, 
    },
    account: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
      vendor: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },

      },
      customer: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },

      },
    },
    stone_master: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
      stone_group: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      stone: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      shape: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },

      size: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      color: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },

      },
      cutting: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      quality: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      clarity: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      certificate_type: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      labour_type: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },

    },
    quotation: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
    },
    reserve: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
    },
    purchaseoder: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
      purchase_order: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      purchaser:{
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
    },
    memo:{
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
      memoin: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      memoinreturn: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
    },
    inventory:{
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
      all: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      primary: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      consignment: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      load: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
    },
    sale: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },

    },
    finance: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
      outstanding_receipt: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      payable: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      receivable: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      },
      transaction: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      }
    },
    report: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
    },
    other: {
      view: { type: Boolean, default: false },
      add: { type: Boolean, default: false },
      edit: { type: Boolean, default: false },
      delete: { type: Boolean, default: false },
      price: { type: Boolean, default: false },
      mainlocation: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      sublocation: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
      currency: {
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
      },
    },
    setup:{
        view: { type: Boolean, default: false },
        add: { type: Boolean, default: false },
        edit: { type: Boolean, default: false },
        delete: { type: Boolean, default: false },
        price: { type: Boolean, default: false },
    },
},},
{ versionKey: false });



module.exports = mongoose.model('User', userSchema);


